apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["/usr/local/bin/att-fiber-gateway-info.sh"]
        env:
        - name: PASSWORD
          value: {{ required "The PASSWORD value is required!" .Values.flags.password | quote }}
        - name: STATSDIPPORT
          value: "{{ .Values.flags.statsdipport }}"
        - name: URL
          value: "{{ .Values.flags.url }}"
